spring:
  application:
    name: ecom-core
logging:
  level:
    org.springframework: info
#server:
#  port: 8882 khong override duoc
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - env
          - metrics
          - prometheus

---
spring:
  profiles:
    active: local
ecom:
  info:
    description: "This is good start, is overridden by local service"
    version: V1.2
  db:
    driver: "com.mysql.jdbc.Driver"
    user: root
    pass: adminadmin
    url: "jdbc:mysql://localhost:3306/mydb"

---
spring:
  profiles:
    active: dev
ecom:
  info:
    description: "This is not overridden"
    version: V1.2
  db:
    driver: "com.mysql.jdbc.Driver"
    user: root
    pass: adminadmin
    url: "jdbc:mysql://localhost:3306/mydb"



